type AddResponse {
  result: Int!
}

type RandomDie {
  ip: String
  numSides: Int!
  rollOnce: Int!
  roll(numRolls: Int!): [Int]
}

input MessageInput {
  content: String
  author: String
}

type Message {
  id: String!
  content: String
  author: String
}

type Query {
  hello: String
  add(a: Int!, b: Int!): AddResponse
  getAll: [Message]
  getMessage(id: ID!): Message
  getDie(numSides: Int): RandomDie
}

type Mutation {
  createMessage(input: MessageInput): Message
  updateMessage(id: ID!, input: MessageInput): Message
}
